---
meta:
  stemcell:
    name: bosh-aws-xen-ubuntu
    version: latest

jobs:
  - name: smoke-tests
    instances: 2
    networks:
      - name: smoke-tests
    properties:
      rabbitmq-smoke-tests:

compilation:
  cloud_properties:
    instance_type: m1.small

resource_pools:
  - name: small_z1
    cloud_properties:
      instance_type: m1.small

networks:
  - name: floating
    type: vip
    cloud_properties: {}
  - name: smoke-tests
    type: dynamic
    cloud_properties:
      security_groups: (( grab meta.security_groups ))
